
import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Header from './components/header';
import Footer from "./components/footer";

// Font loader setup
const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"], // Adjust weights as needed
});

export const metadata: Metadata = {
  title: "Gala",
  description: "A Unique Furniture Gala",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${poppins.className} antialiased bg-white text-zinc-950`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}





























































/*import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Header from './components/header';
import Footer from "./components/footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '700'], // Add weights as per your requirement


});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) { 
 
  return (
    <html lang="en">
      <body
        className={`${Inter} ${poppins} antialiased bg-white text-zinc-950`}
        >
           <Header />
           
        {children}
        
        <Footer />
    
      </body>
    </html>
  );
}*/

/*
import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '700'], // Add weights as per your requirement
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}*/
